# Generated by Django 5.2.7 on 2025-10-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('delivery', 'Delivery Guy'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
    ]
