# Generated by Django 5.2.7 on 2025-10-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('delivery', 'Delivery Guy'), ('handler', 'Handler')], max_length=10),
        ),
    ]
